### ISSUE TITLE
backtracking incorrecto en smith-waterman

### ISSUE THREAD

**Issue by FranciscoDA** [woini2727/bioinformatica#1]
La implementación de smith-waterman comienza el backtracking desde la celda inferior derecha. Debería comenzar desde la celda de mayor score.
https://github.com/woini2727/bioinformatica/blob/master/SmithAlg.py#L43

Ejemplo:
Inputs: `GATTACACACA` y `AAAAAAATAC`

Output obtenido:
```
AC-
ACA
```

Output esperado: 
```
TAC
TAC
```

**Comment by woini2727** [comment]
Fran en la diapo esta distinto.

**Comment by woini2727** [comment]
Fixed.
